name: Frontend CI

on:
  pull_request:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurando Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Instalando dependencias
        run: npm install

      - name: Ejecutando pruebas del frontend
        run: npm test

      - name: Ejecutando linter del frontend
        run: npm run lint
